### PR TITLE
Add deterministic edges patch

### LINKED ISSUE #2: Edge names should be deterministic
If the edges change constantly because they're numbered from e1, e2, e3... then it's a problem. So the eN generation should be replaced with edge names that are deterministic based on resource names. eg: Edge::(File::$name->File::$name2)

This is mentioned here:
https://github.com/purpleidea/mgmt/issues/8#issuecomment-219236367

### PR DESCRIPTION
**Pull request by purpleidea**
Fixes #2

### CODE REVIEW

**Comment by ffrank** [comment]
Cool, thanks! Some thoughts:
 1. the variable name `next_edge` does not feel appropriate anymore
 2. I'd like to add at least one test for this - integration would be suitable, those are also fairly easy to cobble up by now
 3. it doesn't really matter, but the hashing is fairly complex in relation to the goal. Crazy idea: Just work with the original references in `edge["source"]` and `edge["target"]`?

**Comment by purpleidea** [comment]
>    the variable name next_edge does not feel appropriate anymore

Good point, what would you prefer?


>    I'd like to add at least one test for this - integration would be suitable, those are also fairly easy to cobble up by now

I have no idea how to write these, do you want to patch this on afterwards?

>    it doesn't really matter, but the hashing is fairly complex in relation to the goal. Crazy idea: Just work with the original references in edge["source"] and edge["target"]?

What does this mean??

Cheers!

**Comment by ffrank** [comment]
Variable name, `edge_id`?

Test: If you don't wanna, sure, I'll take care of it. It's the fun part after all ;)

Hashing, it currently does `#{from[:kind]}##{from[:name]} -> #{to[:kind]}##{to[:name]}` which is quite a mouthful, with a reference format that is not used anywhere else yet. I was thinking of simplifying this. Or is this format specific in a way I'm missing?

**Comment by purpleidea** [comment]
> Variable name, edge_id?

Sounds good, will update.

> Test: If you don't wanna, sure, I'll take care of it. It's the fun part after all ;)

Awesome! I like you more and more every day!

> Hashing, it currently does #{from[:kind]}##{from[:name]} -> #{to[:kind]}##{to[:name]} which is quite a mouthful, with a reference format that is not used anywhere else yet. I was thinking of simplifying this. Or is this format specific in a way I'm missing?

Right, so I didn't know what to pick, so I tried to pick something that would be fairly unambiguous depending on what the $name variables were. So for example, using / as a split char would be bad because files have them in their names. The -> with spaces felt pretty unique also. Happy to use an alternative.

**Comment by ffrank** [comment]
How about `"#{edge["source"]} -> #{edge["target"]}"`?

**Comment by purpleidea** [comment]
On Tue, May 17, 2016 at 8:45 AM, Felix Frank <notifications@github.com>
wrote:

> How about "#{edge["source"]} -> #{edge["target"]}"?
>


Sounds good. Patch updated.

**Comment by ffrank** [comment]
Looks great! Will merge once I've given it a spin.

Special thanks for the wonderful commit message by the way. 👍

**Comment by purpleidea** [comment]
Written with <3

**Comment by ffrank** [comment]
Thank you for the contribution!

**Pull request merged**
